---
  # This playbook to deploy standalone tomcat9
-
  hosts: Webserver
  become: yes
  remote_user: test
  vars:
    username: admin
    password: adminsecret
    role: "tomcat,admin,manager,manager-gui"
  
  roles:
    - tomcat
...