---
- name: Install nginx
  package:
    name: nginx
    state: present

- name: Copy Configuration file
  template:
     src: "{{config_file_name}}"
     dest: "/etc/nginx/conf.d/"
  notify: restart nginx

- name: Enable Service on startup
  systemd:
    name: nginx
    enabled: yes
    daemon_reload: yes

- name: Start service
  systemd:
    name: nginx
    state: started
    daemon_reload: yes
...