---
- name: Install JAVA 8
  package:
    name: java-1.8.0-openjdk
    state: present
  tags:
    - Install java
  when: tomcat_install_java|bool

- name: add group {{ tomcat_group }}
  group: 
    name: "{{ tomcat_group }}"
  when: tomcat_create_user|bool

- name: add user {{ tomcat_user }}
  user: 
    name:  "{{ tomcat_user }}"
    group: "{{ tomcat_group }}" 
    home: /opt/apache-tomcat-9.0.41
    createhome: no
  when: tomcat_create_user|bool
  

#- name: Download tomcat 9
#  get_url:
#    url: http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.41/bin/apache-tomcat-9.0.41.tar.gz
#    dest: /opt/apache-tomcat-9.0.41.tar.gz

- name: Copy tomcat 9
  copy:
    src: apache-tomcat-9.0.41.tar.gz
    dest: "{{ tomcat_install_path }}/apache-tomcat-9.0.41.tar.gz"
    mode: 0755

- name: Extract Archieve
  unarchive:
    src: "{{ tomcat_install_path }}/apache-tomcat-9.0.41.tar.gz"
    dest: "{{ tomcat_install_path }}/"
    remote_src: yes

- name: Change ownership of Tomcat installation
  file: 
    path: "{{ tomcat_install_path }}/apache-tomcat-9.0.41"
    owner:  "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"  
    state: directory 
    recurse: yes

- name: Configure tomcat server
  template:
    src: "{{ tomcat_template_server }}"
    dest: "{{ tomcat_install_path }}/apache-tomcat-9.0.41/conf/"
  notify: restart tomcat

- name: Configure tomcat users
  template:
    src: "{{ tomcat_template_users }}"
    dest: "{{ tomcat_install_path }}/apache-tomcat-9.0.41/conf/"
  notify: restart tomcat

- name: Install tomcat init script
  template:
    src: "{{ tomcat_template_service }}"
    dest: "{{ tomcat_serice_config_path }}/{{ tomcat_service_name }}.service"
  notify: restart tomcat
    
  
- name: Enable tomcat service on startup
  become: yes
  systemd:
    name: "{{tomcat_service_name}}"
    enabled: yes
    daemon_reload: yes

- name: start {{ tomcat_service_name }}
  become: yes
  systemd:
    name: "{{tomcat_service_name}}"
    state: started
    daemon_reload: yes

  
...